-- DROP SCHEMA posfechados;

CREATE SCHEMA IF NOT EXISTS posfechados AUTHORIZATION lxzehfswwiupap;



-- posfechados.bank definition

-- Drop table

-- DROP TABLE posfechados.bank;

CREATE TABLE posfechados.bank (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	"name" varchar(255) NULL,
	CONSTRAINT bank_name_uk UNIQUE (name),
	CONSTRAINT bank_pkey PRIMARY KEY (id)
);

-- posfechados.client definition

-- Drop table

-- DROP TABLE posfechados.client;

CREATE TABLE posfechados.client (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	ci varchar(255) NULL,
	"name" varchar(255) NULL,
	ruc varchar(255) NULL,
	CONSTRAINT ci_uk UNIQUE (ci),
	CONSTRAINT client_pkey PRIMARY KEY (id)
);

-- posfechados.company definition

-- Drop table

-- DROP TABLE posfechados.company;

CREATE TABLE posfechados.company (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	"name" varchar(255) NULL,
	CONSTRAINT company_name_uk UNIQUE (name),
	CONSTRAINT company_pkey PRIMARY KEY (id)
);


-- posfechados.credit definition

-- Drop table

-- DROP TABLE posfechados.credit;

CREATE TABLE posfechados.credit (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	code varchar(255) NULL,
	description varchar(255) NULL,
	CONSTRAINT credit_code_uk UNIQUE (code),
	CONSTRAINT credit_pkey PRIMARY KEY (id)
);

-- posfechados.currency definition

-- Drop table

-- DROP TABLE posfechados.currency;

CREATE TABLE posfechados.currency (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	code varchar(255) NULL,
	description varchar(255) NULL,
	CONSTRAINT currency_code_uk UNIQUE (code),
	CONSTRAINT currency_pkey PRIMARY KEY (id)
);

-- posfechados.fiscal_year definition

-- Drop table

-- DROP TABLE posfechados.fiscal_year;

CREATE TABLE posfechados.fiscal_year (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	yearfiscal int4 NOT NULL,
	CONSTRAINT fiscal_year_pkey PRIMARY KEY (id),
	CONSTRAINT year_uk UNIQUE (yearfiscal)
);


-- posfechados.postdated_check definition

-- Drop table

-- DROP TABLE posfechados.postdated_check;

CREATE TABLE posfechados.postdated_check (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	account int8 NULL,
	amount float8 NOT NULL,
	checknumber varchar(255) NULL,
	dateexpiration timestamp NULL,
	datepayment timestamp NULL,
	daterecovery timestamp NULL,
	bank_id int8 NOT NULL,
	client_id int8 NOT NULL,
	company_id int8 NOT NULL,
	credit_id int8 NOT NULL,
	currency_id int8 NOT NULL,
	fiscalyear_id int8 NOT NULL,
	CONSTRAINT postdated_check_pkey PRIMARY KEY (id),
	CONSTRAINT postdated_uk UNIQUE (bank_id, client_id, company_id, credit_id, currency_id, fiscalyear_id, account, checknumber)
);


-- posfechados.postdated_check foreign keys

ALTER TABLE posfechados.postdated_check ADD CONSTRAINT posdated_bank_fk FOREIGN KEY (bank_id) REFERENCES posfechados.bank(id);
ALTER TABLE posfechados.postdated_check ADD CONSTRAINT posdated_client_fk FOREIGN KEY (client_id) REFERENCES posfechados.client(id);
ALTER TABLE posfechados.postdated_check ADD CONSTRAINT posdated_company_fk FOREIGN KEY (company_id) REFERENCES posfechados.company(id);
ALTER TABLE posfechados.postdated_check ADD CONSTRAINT posdated_credit_fk FOREIGN KEY (credit_id) REFERENCES posfechados.credit(id);
ALTER TABLE posfechados.postdated_check ADD CONSTRAINT posdated_currency_fk FOREIGN KEY (currency_id) REFERENCES posfechados.currency(id);
ALTER TABLE posfechados.postdated_check ADD CONSTRAINT posdated_fiscalyear_fk FOREIGN KEY (fiscalyear_id) REFERENCES posfechados.fiscal_year(id);


-- posfechados.error_excel definition

-- Drop table

-- DROP TABLE posfechados.error_excel;

CREATE TABLE posfechados.error_excel (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	account int8 NULL,
	amount float8 NOT NULL,
	checknumber varchar(255) NULL,
	dateexpiration timestamp NULL,
	datepayment timestamp NULL,
	daterecovery timestamp NULL,
	information varchar(2000) NULL,
	bank_id int8 NULL,
	client_id int8 NULL,
	company_id int8 NULL,
	credit_id int8 NULL,
	currency_id int8 NULL,
	fiscalyear_id int8 NULL,
	CONSTRAINT error_excel_pkey PRIMARY KEY (id),
	CONSTRAINT log_error_excel_uk UNIQUE (bank_id, client_id, company_id, credit_id, currency_id, fiscalyear_id, account, checknumber)
);


-- posfechados.error_excel foreign keys

ALTER TABLE posfechados.error_excel ADD CONSTRAINT log_bank_fk FOREIGN KEY (bank_id) REFERENCES posfechados.bank(id);
ALTER TABLE posfechados.error_excel ADD CONSTRAINT log_client_fk FOREIGN KEY (client_id) REFERENCES posfechados.client(id);
ALTER TABLE posfechados.error_excel ADD CONSTRAINT log_company_fk FOREIGN KEY (company_id) REFERENCES posfechados.company(id);
ALTER TABLE posfechados.error_excel ADD CONSTRAINT log_credit_fk FOREIGN KEY (credit_id) REFERENCES posfechados.credit(id);
ALTER TABLE posfechados.error_excel ADD CONSTRAINT log_currency_fk FOREIGN KEY (currency_id) REFERENCES posfechados.currency(id);
ALTER TABLE posfechados.error_excel ADD CONSTRAINT log_fiscalyear_fk FOREIGN KEY (fiscalyear_id) REFERENCES posfechados.fiscal_year(id);






